server:
  port: 8888
spring:
  application:
    name: config-server-microservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joserbatista/expman-microservice-config.git
          username: joserbatista
          password: ${GITHUB_TOKEN}
          search-paths: '{application},{application}/{profile}'
eureka:
  instance:
    prefer-ip-address: true