springdoc:
  swagger-ui:
    path: /
spring:
  cloud:
    discovery:
      enabled: true
  data:
    mongodb:
      auto-index-creation: true
      database: expman
      host: localhost
      port: 27017
  application:
    name: transaction-microservice
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    prefer-ip-address: true